# Generated by Django 5.2.7 on 2025-10-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
